### ISSUE TITLE
ng build schema validation with following errors required property outputPath

### ISSUE THREAD

**Issue by chenxu7601257** [Ismaestro/angular9-example-app#56]
Could someone help me out as i was stocked here for lots of time. Thanks. 

Administrator@Jacob MINGW64 /d/源代码/angular8-example
**$ ng build**
**Your global Angular CLI version (8.3.2) is greater than your local
version (8.0.3). The local Angular CLI version is used.**

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Schema validation failed with the following errors:
  **Data path "" should have required property 'outputPath'.
Error: Schema validation failed with the following errors:**
  
```
Data path "" should have required property 'outputPath'.
at MapSubscriber.registry.compile.pipe.operators_1.map [as project] (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\src\architect.js:39:27)
    at MapSubscriber._next (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:145:22)
    at Subscriber._next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\Subscriber.js:145:22)
    at MergeMapSubscriber.notifyNext (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\源代码\angular8-example\node_modules\@angular-devkit\architect\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:145:22)
    at Subscriber._next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\源代码\angular8-example\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)


```

**Comment by Ismaestro** [comment]
Did you modify something in the project??
