### ISSUE TITLE
npm run extract-i18n is not working

### ISSUE THREAD

**Issue by olehleskiv** [Ismaestro/angular9-example-app#60]
**Describe the bug**
Running the `npm run extract-i18n` command throws an error:

```
Error: Schema validation failed with the following errors:
  Data path "" should have required property 'outputPath'.
    at SwitchMapSubscriber.registry.compile.pipe.operators_1.switchMap [as project] (projects/angular8-example-app/node_modules/@angular-devkit/architect/src/architect.js:206:19)
    at SwitchMapSubscriber._next (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:145:22)
    at MergeMapSubscriber.notifyNext (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (projects/angular8-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (projects/angular8-example-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
```

**To Reproduce**
Run `npm run extract-i18n` command 

**Expected behavior**
Expect to extract i18n file

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by Ismaestro** [comment]
Fixed, but https://github.com/angular/angular-cli/issues/17319#issuecomment-626936585
